insert into tiene values('1','1','1','total','titular','34567');
insert into tiene values('2','1','2','parcial','pendiente','78');
insert into tiene values('3','3','1','total','pendiente','4567');
insert into tiene values('4','2','2','parcial','pendiente','46');
insert into tiene values('5','2','1','total','titular','456');
insert into tiene values('6','3','2','total','pendiente','678');
insert into tiene values('7','2','1','parcial','titular','345');
insert into tiene values('7','1','2','parcial','titular','45376');
insert into tiene values('8','3','1','parcial','titular','54');
